#DB setting
spring:
  datasource:
    url: jdbc:mysql://comejun.ddns.net:3306/neargetapi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true
#    url: jdbc:mysql://localhost:3306/neargetapi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true
    username: root
    password: 1234

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight: true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: trace # 시큐리티 관련 로그 남기기

server:
  servlet:
    session:
      tracking-modes: cookie
  port: 8090

#file upload path
nearget.upload.path: upload

#JWT 키
jwt.secret: SGVsbG9Kc29uV2ViVG9rZW5BdXRoZW50aWNhdGlvbldpdGhTcHJpbmdCb290UHJvamVjdFNlY3JldEtleUZvck5lYXJnZXQ