#DB setting
spring:
  datasource:
    url: jdbc:mysql://comejun.ddns.net:3306/neargetapi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true&rewriteBatchedStatements=true
#    url: jdbc:mysql://localhost:3306/neargetapi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 3000
        format_sql: true
        highlight: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: trace # 시큐리티 관련 로그 남기기

decorator:
  datasource:
    p6spy:
      enable-logging: false

server:
  servlet:
    session:
      tracking-modes: cookie
  port: 8090

#file upload path
nearget.upload.path: upload

#JWT 키
jwt.secret: SGVsbG9Kc29uV2ViVG9rZW5BdXRoZW50aWNhdGlvbldpdGhTcHJpbmdCb290UHJvamVjdFNlY3JldEtleUZvck5lYXJnZXQ